### ISSUE TITLE
Question: does React support add any overhead to apps?

### ISSUE THREAD

**Issue by SachaG** [meteor-utilities/avatar#14]
I'm not very familiar with React so sorry if this is a dumb question, but does adding React support to this package implies additional files will be loaded on the client?

If so, maybe the dependency on `react-meteor-data` should be made weak as well?

**Comment by timothyarmes** [comment]
The `react` package is weak linked, so it's not included by this package at all. We detect if it's available before trying to use it. It would certainly be a worry if the entire React runtime were being sent unnecessarily to each client, but that isn't the case.

We do need to include the `jsx` package, otherwise the .jsx file is never compiled. However that only affects the build process - the  `jsx` package isn't sent to the client. Our own .jsx template will be included, but it's tiny. As much common code as possible has been factored out and shared between the Blaze and React template.

Finally, the `react-meteor-data` package should actually be installed as part of the `react` package (if the user's using that), so we **shouldn't** need to include it as a dependency at all. Nevertheless, at least one user had build issues when it wasn't included (see PR #10). This is unfortunate (and incomprehensible), however it is also tiny so it's not worth worrying about. The benefits outweigh the inconvenience in this case.

**Comment by SachaG** [comment]
OK, sounds good to me :) Just wanted to double-check :)

**Comment by jhartma** [comment]
I agree it should be a weak dependency, there's one thing though: when deploying to xxx.meteor.com, the server throws an error saying React is not defined

``` bash
[Wed Aug 05 2015 13:05:41 GMT+0000 (UTC)] WARNING ReferenceError: React is not defined
at packages/utilities:avatar/react/avatar.jsx:8:13
at packages/utilities:avatar/react/avatar.jsx:82:7
at /meteor/containers/3d38624e-5969-f33a-7a65-a2cb56aab446/bundle/programs/server/packages/utilities_avatar.js:528:3
at /meteor/containers/3d38624e-5969-f33a-7a65-a2cb56aab446/bundle/programs/server/boot.js:222:10
at Array.forEach (native)
at Function._.each._.forEach (/meteor/dev_bundles/0.4.18/lib/node_modules/underscore/underscore.js:79:11)
at /meteor/containers/3d38624e-5969-f33a-7a65-a2cb56aab446/bundle/programs/server/boot.js:117:5
[Wed Aug 05 2015 13:05:41 GMT+0000 (UTC)] INFO STATUS running -> waiting
[Wed Aug 05 2015 13:05:41 GMT+0000 (UTC)] ERROR Application crashed with code: 8
[Wed Aug 05 2015 13:05:47 GMT+0000 (UTC)] INFO HIT /favicon.ico 134.76.170.223
```

A little strange that it doesn't pull the dependency.
