### ISSUE TITLE
Colourful background when initials are shown

### ISSUE THREAD

**Issue by raiyankamal** [meteor-utilities/avatar#5]
**Proposal for enhancement**
A project I'm working on requires colourful backgrounds when user's initials are shown in place of avatar images. Much like the Gmail app. Do others find this feature useful? If yes, I'll send a pull request to merge this functionality.

**Comment by timothyarmes** [comment]
Sure, go ahead.

Using the new CSS generation introduced in 0.7.15 is should now be trivial to add that as a global option.

You should also ensure that it's possible to override the background colour on a per-avatar basis.

**Comment by raiyankamal** [comment]
Thanks. This is what I have in mind, feel free to give your feedback / comments:

Default config should be an internal function that assigns background colour based on the user's initials. One can also write their own function to map initials to colour values and assign that to reconfigure the avatar package.

**Comment by timothyarmes** [comment]
Ah, so you wish to change the colour based on the initials? Interesting. 

My initial expectations were that you would provide a simple background colour as an global option (since right now it's fixed), however I can see the value in your suggestion.

In that case this might be the best approach:
1. Allow the user to globally change the background colour for the base case (that would just alter the generated CSS)
2. Optionally allow them to pass a function instead. In this case the generated CSS isn't changed, but you need to style each individual avatar using the HTML style attribute.
3. Also allow them to specify a colour as part of the template, so that they can use a template helper function on a per avatar basis.

Thoughts?

**Comment by timothyarmes** [comment]
The latest release now allows you specify background/text colors globally. It was already possible to override them locally.

All that's left is to provide a function for overriding them.

**Comment by raiyankamal** [comment]
I've sent a pull request today. 
If this looks good, please feel free to close this issue.

**Comment by timothyarmes** [comment]
Hi,

That's cool. I've added a few change requests in the pull issue.

Thanks,

Tim

**Comment by raiyankamal** [comment]
You got a really good point there. I've refactored the code to leave out the hardcoded color scheme. Also modified the react template. Have a look when you have time. Thanks.

**Comment by timothyarmes** [comment]
That's great. I've made another request that's just occurred to me; it's keep the API simpler.`
Tim

**Comment by raiyankamal** [comment]
Good suggestion. Its done.

**Comment by timothyarmes** [comment]
Just one small thing left - you forgot to remove some code.

**Comment by raiyankamal** [comment]
Thanks for pointing that out. Done.

**Comment by timothyarmes** [comment]
Thanks, merged.
